name: Build and Deploy

on:
  push:
    branches:
      - 'projects-and-emps'

jobs:
  test:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm build
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
			with:
				key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy
      run: rsync -navz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/users/l/leadertask/domains/app.leadertask.ru/
